### PR TITLE
Allow read-only access to the icons directories and change XCURSOR_PATH to match

### PR DESCRIPTION
**Pull request by catgirlcataclysm**
Without doing it like this, I was unable to get anything other than the fallback cursor to work on Wayland. I'd understand if this is frowned upon, as it does slightly weaken the sandbox. I'd love suggestions as to other ways to accomplish this

### CODE REVIEW

**Comment by catgirlcataclysm** [comment]
you see now im just embarrassed lmao ill fix this rq

**Comment by catgirlcataclysm** [comment]
yup i have no idea how to fix this and the documentation is about as helpful as glasses are for a jellyfish

**Comment by lewisakura** [comment]
resolved upstream issue with appstream file

bot, build

**Comment by lewisakura** [comment]
bot, build

**Comment by JakobDev** [comment]
Which Desktop are you using?

**Comment by catgirlcataclysm** [comment]
Gnome, whatever version is newest on arch.

**Comment by JakobDev** [comment]
That's a Issue of Gnome. Gnome needs to [implement the cursor shape protcol](https://gitlab.gnome.org/GNOME/mutter/-/issues/3276) to fix this.

**Comment by catgirlcataclysm** [comment]
> That's a Issue of Gnome. Gnome needs to [implement the cursor shape protcol](https://gitlab.gnome.org/GNOME/mutter/-/issues/3276) to fix this.

Oh, Well in that case I'll be closing this, Thank you!

**Pull request closed without merging**
