### PR TITLE
Update to version 1.5.2

### LINKED ISSUE #16: [Enhancement] Upgrade to version 1.5.2
Hi, there's new version:
https://github.com/Vencord/Vesktop/releases/tag/v1.5.2

Thanks 🙏 and let's goo 🚀!

### PR DESCRIPTION
**Pull request by Stoppedpuma**
Closes #16

### CODE REVIEW

**Comment by Stoppedpuma** [comment]
bot, build

**Comment by linux-universe** [comment]
Works perfectly

**Comment by lewisakura** [comment]
not sure why flathubbot didn't PR this... it's meant to do it

**Comment by Venefilyn** [comment]
Didn't seem to get published either, something seems up with the bot
@lewisakura can you publish manually?

**Comment by Stoppedpuma** [comment]
> Didn't seem to get published either, something seems up with the bot @lewisakura can you publish manually?

The update should be available now

**Comment by Venefilyn** [comment]
> The update should be available now

Yep that solved it, thanks a lot!

**Pull request merged**
