### PR TITLE
fix launching when WAYLAND_DISPLAY is absolute path

### PR DESCRIPTION
**Pull request by Vendicated**

### CODE REVIEW

**Comment by ThaCheeseBun** [comment]
Yup, this seems to fix it. It launches and im getting the `Wayland socket is available, running natively on Wayland. To disable, remove the --socket=wayland permission.` message :+1:.

**Comment by Laertes87** [comment]
I think I'm still encountering a different issue then as it still won't start:
```
$ flatpak run dev.vencord.Vesktop 
Using NVIDIA on Wayland, disabling gpu sandbox
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --disable-gpu-sandbox --ozone-platform-hint=auto
[3:0705/142720.907280:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden


#
# Fatal process out of memory: Failed to reserve virtual memory for CodeRange
#
----- Native stack trace -----

/app/bin/startvesktop: Zeile 26:     3 Trace/Breakpoint ausgelöst   zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
```

`/run/dbus/system_bus_socket: File or directory not found`

Maybe still some weird interaction with Gnome?

**Comment by ThaCheeseBun** [comment]
I also got this error in my logs but it does not seem to affect anything for me on Plasma. You could try enabling "D-Bus system bus" using flatseal and see if it helps, but i think it's something else.

**Comment by Laertes87** [comment]
I tried that but it unfortunately makes no difference. The app would still not start for me. This is the most recent output:
```
$ flatpak run dev.vencord.Vesktop 
Using NVIDIA on Wayland, disabling gpu sandbox
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --disable-gpu-sandbox --ozone-platform-hint=auto
[3:0705/144620.140541:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0705/144620.333597:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[3:0705/144620.333636:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[3:0705/144620.449267:ERROR:browser_main_loop.cc(278)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[3:0705/144620.495932:ERROR:wayland_event_watcher.cc(68)] Fatal Wayland communication error: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt.
[3:0705/144620.495982:FATAL:electron_browser_main_parts.cc(503)] Failed to shutdown.
/app/bin/startvesktop: Zeile 26:     3 Trace/Breakpoint ausgelöst   zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
```

My guess is that the ERR_CONNECTION_RESET could be the culprit here: `[3:0705/144620.495932:ERROR:wayland_event_watcher.cc(68)] Fatal Wayland communication error: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt.`

**Comment by Erwin-Iosef** [comment]
It works for me! Vesktop appears and runs. Hope this gets repaired soon.
Here's the log:
```
~$ flatpak run dev.vencord.Vesktop
F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto
[3:0705/192005.571502:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0705/192005.914919:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0705/192005.915023:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[Vencord] Installed React Developer Tools
(node:3) ExtensionLoadWarning: Warnings loading extension at /home/admin2/.var/app/dev.vencord.Vesktop/config/vesktop/ExtensionCache/fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

(Use `vesktop.bin --trace-warnings ...` to show where the warning was created)
[3:0705/192009.496479:ERROR:nss_util.cc(227)] Error initializing NSS with a persistent database (sql:/home/admin2/.pki/nssdb): NSS error code: -8126

```

**Comment by Parilia** [comment]
It runs for about 5 seconds and then kills its self, no idea why as terminal doesn't say anything.

**Pull request merged**
