### PR TITLE
fix appindicator icon

### LINKED ISSUE #2: Tray icon is missing
Vesktop has no icon in the tray.

tested with Vesktop v0.4.4, `appindicatorsupport@rgcjonas.gmail.com` 53, gnome 44, Fedora Workstation 38. 

The icon for other apps loads correctly, as you can see in the screenshot below.

image

### PR DESCRIPTION
**Pull request by SoMuchForSubtlety**
Fixes #2

### CODE REVIEW

**Comment by SoMuchForSubtlety** [comment]
> Build [94082 successful](https://buildbot.flathub.org/#/builders/6/builds/94082) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/76827/dev.vencord.Vesktop.flatpakref
> ```

Fixes the issue for me

**Comment by SoMuchForSubtlety** [comment]
It just saw that the start script sets the `TMPDIR` variable, but AFAICT that has no effect.

https://github.com/flathub/dev.vencord.Vesktop/blob/1e709af7f51e282a702850744d73f240f1dfaab2/startvesktop#L3

**Comment by Vendicated** [comment]
indeed, that line should be `export TMPDIR=`

**Comment by SoMuchForSubtlety** [comment]
> indeed, that line should be `export TMPDIR=`

Do you want me to revert my changes and fix the startup script instead?

**Comment by lewisakura** [comment]
yes, that is a typo that i did not notice - try locally first and see if it works if changed to `export TMPDIR`, then update the PR

**Comment by SoMuchForSubtlety** [comment]
Do you want any more changes?

**Comment by azzamsa** [comment]
Hi, 👋.

Any reason this PR is not getting merged?
The tray icon/status was very crucial for my workflow.

Thank you for maintaining Vesktop!

**Comment by lewisakura** [comment]
waiting for it to be tested by more people on a variety of machines, if you would like to help please install it and see if it fixes the issue.

**Pull request merged**
